### ISSUE TITLE
Impossible de charger le script de l’extension

### ISSUE THREAD

**Issue by Txori** [xaviermonin/Rope#1]
Bonjour, je suis nouveau sur Godot et cela fait quelques jours que je bataille sur la création d'une corde dynamique entre deux KyneticBody2D. Mais mon résultat n'est pas génial...

Du coup, j'ai fini par tomber sur votre extension, mais je ne peux pas l'activer dans les paramètres du projet:
```
Impossible de charger le script de l’extension depuis le chemin : « res://addons/GSharpRope/GSharpRopePlugin.cs ». Il semble y avoir une erreur dans le code, merci de vérifier la syntaxe.
```
Le truc c'est que je n'arrive pas à activer Debug/Deploy to local Windows dans Visual Studio pour en savoir plus sur cette "erreur".
(https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html)

Pouvez-vous m'aider ?

**Comment by xaviermonin** [comment]
Bonjour,

Pour la mise en place d'un projet Godot en C# je t'encourage à lire l'article suivant : https://giulianob.svbtle.com/godot-csharp-setup

Pour régler l'erreur, il faut générer une première fois le projet avec Godot (le bouton en haut à droite) afin que la version compilée de l'addon soit disponible dans l'editeur. Ca créera le répertoire .mono qui contient les builds et qui est utilisé par Godot.
![Génération](https://user-images.githubusercontent.com/5740369/107118181-a8f9a380-687f-11eb-904f-8ed11534796a.png)

Un autre point important, il faut que la version de C# soit 8 ou plus. Ca se change dans le fichier projet en ajoutant ou modifiant : `<LangVersion>8.0</LangVersion>` dans le noeud PropertyGroup.
![CSharpVersion](https://user-images.githubusercontent.com/5740369/107118260-24f3eb80-6880-11eb-9fcd-9eaa228311ee.png)


Je te met en pièce jointe une version minimale de test de l'addon. Tu aura l'erreur à l'ouverture mais après avoir généré le projet Godot, tu ne l'aura plus : [TestGSharpRope.zip](https://github.com/xaviermonin/GSharpRope/files/5936793/TestGSharpRope.zip)

![En action](https://user-images.githubusercontent.com/5740369/107118193-b31ba200-687f-11eb-81d8-d611802cccc9.png)

**Comment by Txori** [comment]
Merci beaucoup pour l'explication. En fait j'avais complètement loupé le bouton build...

Mais après plusieurs tests, la gestion "physique" de la corde en plusieurs segments ne me convient pas dans mon cas. Et je n'aime pas trop avoir à installer Visual Studio alors que le côté portable de Godot était parfait pour mon utilisation.

Du coup je me suis lancé dans des segments de corde qui ne se créent que lorsqu'une collision est détectée. La corde est très raide, mais plus réactive. Puis je vais afficher un Verlet rope (https://www.youtube.com/watch?v=MeFZbiJM8zo) en utilisant les points de ma corde raide pour rendre quelque chose de plus souple visuellement.

**Comment by xaviermonin** [comment]
Pour faire une corde plus souple il faut jouer avec les paramètres Linear Damp et Angular Damp sur les RopePart (dans addons/GSharpRope/RopePart.tscn). Il y a aussi les paramètres du joint qui sont importants (la softness et le bias). On peut aussi jouer sur le nombre de pièces (Curve => Bake Interval).

Je t'es mis en pièce jointe un exemple de corde souple en jouant avec les paramètres indiqués. Ce n'est pas parfait, mais si ca peut t'aider.
[Corde souple.zip](https://github.com/xaviermonin/GSharpRope/files/5950838/Corde.souple.zip)

Mais en effet, si tu veux quelque chose de très dynamique, une corde basée sur la physique ne me parait pas approprié.

**Comment by xaviermonin** [comment]
Petit complément qui m'a aidé dans le test du plugin : https://www.youtube.com/watch?v=17GjWTZ-2Ik&feature=youtu.be&t=4910

**Comment by Txori** [comment]
Ah top. Merci pour le lien !
